<?php 
/**
 * Cronjob Scheduler Include File
 *
 * This page allows you to create Cronjob Scheduler custom actions
 * through the WordPress admin. Actions can also be created within
 * theme files or other PHP files throughout your WordPress install.
 *
 * Do not edit this file unless you have a good understanding of PHP, 
 * saving this with invalid code can render your WordPress install inoperable
 * until you can fix the issue using FTP or another file editing utility.
**/

include('../../../wp-config.php');

function my_cronjob_action () {

    // code to execute on cron run
	// the message
	$msg = "First line of text\n\nSecond line of text";
	// use wordwrap() if lines are longer than 70 characters
	$msg = wordwrap($msg,70);
	//headers
	$headers = 'From: Right Advice <info@curedincurable.com>' . "\r\n" .
		'Reply-To: info@curedincurable.com' . "\r\n" .
		'X-Mailer: PHP/' . phpversion();
	// send email
	mail("nagendra_singh@opiant.in","My subject Test",$msg,$headers);

} add_action('my_cronjob_action', 'my_cronjob_action');


function weekly_email_lawyer() {

	//select all active lawyers
	$lawyers_query = mysql_query("SELECT id as lawyer_id, email as lawyer_email FROM ra_lawyers WHERE status = 1") or die(mysql_error());
	while ($lawyer_row = mysql_fetch_assoc($lawyers_query))
	{
		//select all unanswered questions of the lawyer
		$question_query = mysql_query("SELECT a.subject as question_subject, a.content as question_content, a.added_date as question_date, b.full_name as client_name FROM ra_question a, ra_front_users b WHERE a.lawyer_id = '" . $lawyer_row['lawyer_id'] . "' AND a.client_id = b.id");
		$question_count = 0;
		$message_1 = '';
		$message_2 = '';
		$message_3 = '';
		$message_1 = '<html>
    <head>
        <title>Right Advice</title>
    </head>
    <body>
	
			<table align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee" style="width:100%!important">
                <tbody>
                	<tr>
                    	<td>
                			<table width="690" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee">
                            <tbody>
                            	<tr>
                                    <td colspan="3" height="80" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee" style="padding:0;margin:0;font-size:0;line-height:0">
                                        <table width="690" align="center" border="0" cellspacing="0" cellpadding="0">
                                        <tbody>
                                        	<tr>
                                            	<td width="30">&nbsp;</td>
                                                <td align="center" valign="middle" style="padding:0;margin:0;font-size:0;line-height:0"><a href="http://curedincurable.com/rightadvice" target="_blank"><img src="http://curedincurable.com/rightadvice/wp-content/themes/right_advice/images/logo.jpg"></a></td>
                                                <td width="30">&nbsp;</td>
                                            </tr>
                                       	</tbody>
                                        </table>
                                  	</td>
                    			</tr>
                                <tr>
                                    <td colspan="3" align="center">
                                        <table width="630" align="center" border="0" cellspacing="0" cellpadding="0">
			<tbody>
				<tr>
					<td align="center" height="60"><h1 style="font-family:HelveticaNeue-Light,arial,sans-serif;font-size:48px;color:#404040;line-height:48px;font-weight:bold;margin:0;padding:0">Ask A Question Summary</h1></td>				
				</tr>
				<tr>
					<td height="60"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b><i>Client is awaiting response to below Questions. Please respond at the earliest.</i></b></p></td>
				</tr>
				<tr>
			<table align="left" border="1" cellspacing="0" cellpadding="2" bgcolor="#eeeeee" style="width:100%!important">
				<tbody>
					<tr>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>S. No.</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Client Name</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Subject</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Question</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Date</b></p></th>
					</tr>';
		while ($question_row = mysql_fetch_assoc($question_query))
		{
			$question_count++;
			//creating table of unanswered questions
			$message_2 .= '<tr>
					<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$question_count.'.</p></td>
					<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$question_row['client_name'].'</p></td>
					<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$question_row['question_subject'].'</p></td>
					<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$question_row['question_content'].'</p></td>
					<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.date('d F, Y', strtotime($question_row['question_date'])).'</p></td>
				</tr>';
		}
		$message_3 = '</tbody>
			</table>
			</tr>
			</tbody>
										</table>
                  			<table align="center" width="750px" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee" style="width:750px!important">
                            <tbody>
                            	<tr>
                                	<td>
                                        <table width="630" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee">
                                        <tbody>
                                        	<tr><td colspan="2" height="30">&nbsp;</td></tr>
                                            <tr>
                                            	<td width="360" valign="top">
                                                	<div style="color:#a3a3a3;font-family:HelveticaNeue-Light,arial,sans-serif; font-size:12px;line-height:12px;padding:0;margin:0">&copy; 2017 Right Advice. All rights reserved.</div>
                                        		</td>
                                              	<td align="right" valign="top">
                                                	&nbsp;
                                              	</td>
                                            </tr>
                                            <tr><td colspan="2" height="5">&nbsp;</td></tr>
                                           
                                      	</tbody>
                                        </table>
                                   	</td>
                  				</tr>
                          	</tbody>
                            </table>
                  		</td>
                	</tr>
              	</tbody>
			</table>
    
</body>
</html>';
		if ($question_count > 0)
		{
			//prepare_message
			$lawyer_email_message = $message_1 . $message_2 . $message_3;
			//send email
			$lawyer_email_to = $lawyer_row['lawyer_email'];
			$lawyer_email_subject = "Right Advice | Weekly Summary Report";
			//headers
			$headers  = 'MIME-Version: 1.0' . "\r\n";
			$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
			$headers .= 'From: Right Advice <info@curedincurable.com>' . "\r\n" .
				'Reply-To: info@curedincurable.com' . "\r\n" .
				'X-Mailer: PHP/' . phpversion();
			mail($lawyer_email_to, $lawyer_email_subject, $lawyer_email_message, $headers);
		}
	}
	mail("nagendra_singh@opiant.in", "Summary Email sent to Lawyers", "Summary Email sent to Lawyers", $headers);
	
} add_action('weekly_email_lawyer', 'weekly_email_lawyer');

function weekly_email_admin() {

	//select all admin emails
	$admin_query = mysql_query("SELECT distinct admin_email FROM ra_lawyers WHERE status = 1 AND admin_email !=''") or die(mysql_error());
	//mail("nagendra_singh@opiant.in", "Query 1", "SELECT distinct admin_email FROM ra_lawyers WHERE status = 1 AND admin_email !=''");
	while ($admin_row = mysql_fetch_assoc($admin_query))
	{
		//select all lawyers for an admin
		$lawyer_query = mysql_query("SELECT id as lawyer_id, full_name as lawyer_name FROM ra_lawyers WHERE status = 1 AND admin_email = '" . $admin_row['admin_email'] . "'") or die(mysql_error());
		//mail("nagendra_singh@opiant.in", "Query 2", "SELECT id as lawyer_id, full_name as lawyer_name FROM ra_lawyers WHERE status = 1 AND admin_email = '" . $admin_row['admin_email'] . "'");
		$question_count = 0;
		$message_1 = '';
		$message_2 = '';
		$message_3 = '';
		$message_1 = '<html>
    <head>
        <title>Right Advice</title>
    </head>
    <body>
	
			<table align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee" style="width:100%!important">
                <tbody>
                	<tr>
                    	<td>
                			<table width="690" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee">
                            <tbody>
                            	<tr>
                                    <td colspan="3" height="80" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee" style="padding:0;margin:0;font-size:0;line-height:0">
                                        <table width="690" align="center" border="0" cellspacing="0" cellpadding="0">
                                        <tbody>
                                        	<tr>
                                            	<td width="30">&nbsp;</td>
                                                <td align="center" valign="middle" style="padding:0;margin:0;font-size:0;line-height:0"><a href="http://curedincurable.com/rightadvice" target="_blank"><img src="http://curedincurable.com/rightadvice/wp-content/themes/right_advice/images/logo.jpg"></a></td>
                                                <td width="30">&nbsp;</td>
                                            </tr>
                                       	</tbody>
                                        </table>
                                  	</td>
                    			</tr>
                                <tr>
                                    <td colspan="3" align="center">
                                        <table width="630" align="center" border="0" cellspacing="0" cellpadding="0">
			<tbody>
				<tr>
					<td align="center" height="60"><h1 style="font-family:HelveticaNeue-Light,arial,sans-serif;font-size:48px;color:#404040;line-height:48px;font-weight:bold;margin:0;padding:0">Ask A Question Summary</h1></td>				
				</tr>
				<tr>
					<td height="60"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b><i>Client is awaiting response to below Questions. Please respond at the earliest.</i></b></p></td>
				</tr>
				<tr>
			<table align="left" border="1" cellspacing="0" cellpadding="2" bgcolor="#eeeeee" style="width:100%!important">
				<tbody>
					<tr>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>S. No.</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Lawyer Name</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Client Name</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Subject</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Question</b></p></th>
						<th><p style="color:#404040;font-size:14px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0"><b>Date</b></p></th>
					</tr>';
		while ($lawyer_row = mysql_fetch_assoc($lawyer_query))
		{
			//select all unanswered questions of the lawyer
			$question_query = mysql_query("SELECT a.subject as question_subject, a.content as question_content, a.added_date as question_date, b.full_name as client_name FROM ra_question a, ra_front_users b WHERE a.lawyer_id = '" . $lawyer_row['lawyer_id'] . "' AND a.client_id = b.id");
			//mail("nagendra_singh@opiant.in", "Query 3", "SELECT a.subject as question_subject, a.content as question_content, a.added_date as question_date, b.full_name as client_name FROM ra_question a, ra_front_users b WHERE a.lawyer_id = '" . $lawyer_row['lawyer_id'] . "' AND a.client_id = b.id");
			while ($question_row = mysql_fetch_assoc($question_query))
			{
				$question_count++;
				//creating table of unanswered questions
				$message_2 .= '<tr>
						<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$question_count.'.</p></td>
						<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$lawyer_row['lawyer_name'].'</p></td>
						<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$question_row['client_name'].'</p></td>
						<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$question_row['question_subject'].'</p></td>
						<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.$question_row['question_content'].'</p></td>
						<td align="center"><p style="color:#404040;font-size:12px; line-height:22px; font-family:HelveticaNeue-Light,arial,sans-serif; font-weight:lighter; padding:0;margin:0">'.date('d F, Y', strtotime($question_row['question_date'])).'</p></td>
					</tr>';
			}
			$message_3 = '</tbody>
			</table>
			</tr>
			</tbody>
										</table>
                  			<table align="center" width="750px" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee" style="width:750px!important">
                            <tbody>
                            	<tr>
                                	<td>
                                        <table width="630" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#eeeeee">
                                        <tbody>
                                        	<tr><td colspan="2" height="30">&nbsp;</td></tr>
                                            <tr>
                                            	<td width="360" valign="top">
                                                	<div style="color:#a3a3a3;font-family:HelveticaNeue-Light,arial,sans-serif; font-size:12px;line-height:12px;padding:0;margin:0">&copy; 2017 Right Advice. All rights reserved.</div>
                                        		</td>
                                              	<td align="right" valign="top">
                                                	&nbsp;
                                              	</td>
                                            </tr>
                                            <tr><td colspan="2" height="5">&nbsp;</td></tr>
                                           
                                      	</tbody>
                                        </table>
                                   	</td>
                  				</tr>
                          	</tbody>
                            </table>
                  		</td>
                	</tr>
              	</tbody>
			</table>
			</body>
			</html>';
		}
		if ($question_count > 0)
		{
			//prepare_message
			$admin_email_message = $message_1 . $message_2 . $message_3;
			//send email
			$admin_email_to = $admin_row['admin_email'];
			$admin_email_subject = "Right Advice | Weekly Summary Report (All Lawyers)";
			//headers
			$headers  = 'MIME-Version: 1.0' . "\r\n";
			$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
			$headers .= 'From: Right Advice <info@curedincurable.com>' . "\r\n" .
				'Reply-To: info@curedincurable.com' . "\r\n" .
				'X-Mailer: PHP/' . phpversion();
			mail($admin_email_to, $admin_email_subject, $admin_email_message, $headers);
		}
	}
	mail("nagendra_singh@opiant.in", "Summary Email sent to Lawyer Administrators", "Summary Email sent to Lawyer Administrators", $headers);
	
} add_action('weekly_email_admin', 'weekly_email_admin');
